apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: k8s-demo
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
