{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-demo.fullname" . }}-ingress
  namespace: {{ include "k8s-demo.namespace" . }}
  labels:
    {{- include "k8s-demo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- include "k8s-demo.ingress.paths" (dict "paths" .paths "Values" $.Values "Release" $.Release "Chart" $.Chart) | nindent 6 }}
  {{- end }}
{{- end }}