{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-demo.fullname" . }}-frontend
  namespace: {{ include "k8s-demo.namespace" . }}
  labels:
    {{- include "k8s-demo.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "k8s-demo.frontend.selectorLabels" . | nindent 4 }}
{{- end }}

