{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-demo.fullname" . }}-backend
  namespace: {{ include "k8s-demo.namespace" . }}
  labels:
    {{- include "k8s-demo.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "k8s-demo.backend.selectorLabels" . | nindent 4 }}
{{- end }}

