apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend-vpa
  namespace: k8s-demo
  labels:
    app: backend
    component: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: "Off"  # Start with Off mode for data collection
  resourcePolicy:
    containerPolicies:
    - containerName: backend
      maxAllowed:
        cpu: "1"
        memory: "2Gi"
      minAllowed:
        cpu: "50m"
        memory: "128Mi"
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
