apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpa-monitor
  namespace: k8s-demo
  labels:
    app: vpa
spec:
  selector:
    matchLabels:
      app: vpa-recommender
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
