apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-demo
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP
