apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: k8s-demo
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
